wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
config_save_path:
  value: models/sweep_config.json
dataset:
  value: mnist
epochs:
  value: 30
hidden_size:
  value: 64
learning_rate:
  value: 0.0008035504083106707
loss:
  value: cross_entropy
model_save_path:
  value: models/sweep_model.npy
no_sweep_yaml:
  value: true
num_layers:
  value: 3
optimizer:
  value: nadam
seed:
  value: 42
wandb_entity:
  value: rbhdsks-iitm
weight_decay:
  value: 0.0003954739025025887
weight_init:
  value: random
