wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
config_save_path:
  value: models/sweep_config.json
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 64
learning_rate:
  value: 0.0019922443455350023
loss:
  value: cross_entropy
model_save_path:
  value: models/sweep_model.npy
no_sweep_yaml:
  value: true
num_layers:
  value: 2
optimizer:
  value: rmsprop
seed:
  value: 21
wandb_entity:
  value: rbhdsks-iitm
weight_decay:
  value: 0.0006936827592863632
weight_init:
  value: xavier
